# Copyright (c) 2020 Oracle and/or its affiliates. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Distribution License v. 1.0, which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: BSD-3-Clause
#

language: java

dist: bionic

git:
  depth: false
  
jobs:
  include:
    - arch: amd64
      jdk: oraclejdk11
    - arch: amd64
      jdk:  oraclejdk14
    - arch: ppc64le
      jdk: openjdk11

cache:
  directories:
    - .autoconf
    - $HOME/.m2

script:
  - mvn -B -V -U -C -Poss-release clean verify org.glassfish.copyright:glassfish-copyright-maven-plugin:check -Dgpg.skip=true
